
import React, { createContext, useContext, useState } from 'react';

export type Language = 'pt' | 'en' | 'es';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  pt: {
    app_name: "RoutineMaster",
    app_subtitle: "Gestão Industrial",
    login_title: "Gestão de Rotina Industrial",
    login_user: "Email ou Usuário",
    login_pass: "Senha",
    login_btn: "Entrar",
    login_error_auth: "Credenciais inválidas. Verifique seu email e senha.",
    login_demo: "Credenciais Demo:",
    nav_dashboard: "Painel",
    nav_routine: "Minha Rotina",
    nav_logs: "Registros",
    nav_admin: "Gestão & Admin",
    nav_insights: "Consultor IA",
    nav_logout: "Sair do Sistema",
    dash_title: "Painel de Controle",
    dash_subtitle: "Visão geral de disciplina e produtividade",
    dash_top_performer: "Colaborador Destaque",
    dash_discipline: "de Disciplina Atual",
    dash_rate: "Taxa Geral de Adesão",
    dash_team: "da equipe",
    dash_pending: "Tarefas Pendentes",
    dash_pending_sub: "Atividades não realizadas no período",
    dash_ranking: "Ranking de Disciplina (Período Atual)",
    dash_prod_chart: "Volume de Produção vs Refugo (Últimos 7 dias)",
    dash_filter_shift: "Filtrar por Turno:",
    dash_filter_dept: "Filtrar por Setor:",
    dash_all_shifts: "Todos os Turnos",
    dash_all_depts: "Todos os Setores",
    routine_title: "Minha Rotina",
    routine_subtitle: "Atividades programadas",
    routine_completed: "Concluídas",
    routine_empty: "Nenhuma tarefa atribuída a você.",
    routine_overdue: "ATRASADO",
    routine_until: "Até",
    routine_placeholder: "Observação (opcional)",
    routine_value_ph: "Valor",
    routine_btn_complete: "Concluir",
    routine_status_done: "Concluído",
    routine_out_of_range: "Fora da faixa",
    logs_title: "Registros Operacionais",
    logs_subtitle: "Informe dados de produção, ocorrências e paradas.",
    log_prod: "Produção",
    log_scrap: "Refugo",
    log_stop: "Parada",
    log_maint: "Manutenção",
    log_label_time: "Tempo (minutos)",
    log_label_qty: "Quantidade (peças)",
    log_label_val: "Valor / Quantidade",
    log_label_desc: "Descrição / Observação",
    log_place_desc: "Descreva o motivo, código da peça ou detalhe da ocorrência...",
    log_btn_save: "Registrar Apontamento",
    log_success: "Registro salvo com sucesso!",
    log_history: "Histórico Recente",
    log_btn_delete: "Excluir",
    admin_tab_tasks: "Gestão de Rotinas",
    admin_tab_users: "Colaboradores",
    admin_tab_reports: "Relatórios Globais",
    admin_new_user: "Novo Colaborador",
    admin_new_task: "Nova Rotina",
    admin_ph_name: "Nome Completo",
    admin_ph_user: "Usuário (Login)",
    admin_ph_email: "Email Corporativo",
    admin_ph_pass: "Senha de Acesso",
    admin_ph_title: "Cargo (Ex: Mecânico)",
    admin_ph_shift: "Turno",
    admin_ph_dept: "Departamento (Ex: Manutenção)",
    admin_role_op: "Operacional",
    admin_role_adm: "Administrador",
    admin_btn_add_user: "Cadastrar",
    admin_ph_task_title: "Título da Atividade",
    admin_ph_task_desc: "Instruções",
    admin_label_assign: "Atribuir a:",
    admin_btn_add_task: "Criar Rotina",
    admin_confirm_user: "Tem certeza que deseja remover este usuário?",
    admin_confirm_task: "Tem certeza que deseja remover esta rotina?",
    admin_confirm_log: "Tem certeza que deseja excluir este registro?",
    admin_responsibles: "responsáveis",
    admin_type: "Tipo de Tarefa",
    admin_type_check: "Checklist Simples",
    admin_type_meas: "Medição/Coleta de Dados",
    admin_unit: "Unidade (ex: bar, °C)",
    admin_min: "Mín",
    admin_max: "Máximo",
    admin_export_csv: "Exportar Dados (CSV)",
    report_date: "Data",
    report_user: "Usuário",
    report_type: "Tipo",
    report_value: "Valor",
    report_desc: "Descrição",
    insights_title: "Consultor IA",
    insights_intro: "Utilize a inteligência artificial para analisar padrões de refugo, paradas e disciplina da equipe.",
    insights_btn: "Gerar Plano de Ação",
    insights_btn_loading: "Analisando...",
    insights_result_title: "Plano Estratégico Generado",
    insights_empty: "Clique no botão acima para gerar insights baseados nos dados atuais.",
    freq_hourly: "HORA A HORA",
    freq_daily: "DIÁRIO",
    freq_weekly: "SEMANAL",
    freq_monthly: "MENSAL",
    freq_yearly: "ANUAL"
  },
  en: {
    app_name: "RoutineMaster",
    app_subtitle: "Industrial Management",
    login_title: "Industrial Routine Management",
    login_user: "Email or Username",
    login_pass: "Password",
    login_btn: "Login",
    login_error_auth: "Invalid credentials. Check email and password.",
    login_demo: "Demo Credentials:",
    nav_dashboard: "Dashboard",
    nav_routine: "My Routine",
    nav_logs: "Logs",
    nav_admin: "Admin & Mgmt",
    nav_insights: "AI Advisor",
    nav_logout: "Logout",
    dash_title: "Dashboard",
    dash_subtitle: "Overview of discipline and productivity",
    dash_top_performer: "Top Performer",
    dash_discipline: "Current Discipline",
    dash_rate: "Adherence Rate",
    dash_team: "of team",
    dash_pending: "Pending Tasks",
    dash_pending_sub: "Activities not done in period",
    dash_ranking: "Discipline Ranking (Current Period)",
    dash_prod_chart: "Production Volume vs Scrap (Last 7 Days)",
    dash_filter_shift: "Filter by Shift:",
    dash_filter_dept: "Filter by Dept:",
    dash_all_shifts: "All Shifts",
    dash_all_depts: "All Depts",
    routine_title: "My Routine",
    routine_subtitle: "Scheduled activities",
    routine_completed: "Completed",
    routine_empty: "No tasks assigned to you.",
    routine_overdue: "OVERDUE",
    routine_until: "By",
    routine_placeholder: "Note (optional)",
    routine_value_ph: "Value",
    routine_btn_complete: "Complete",
    routine_status_done: "Completed",
    routine_out_of_range: "Out of range",
    logs_title: "Operational Logs",
    logs_subtitle: "Report production, occurrences, and downtime.",
    log_prod: "Production",
    log_scrap: "Scrap",
    log_stop: "Downtime",
    log_maint: "Maintenance",
    log_label_time: "Time (minutes)",
    log_label_qty: "Quantity (units)",
    log_label_val: "Value / Quantity",
    log_label_desc: "Description / Note",
    log_place_desc: "Describe reason, part code, or occurrence detail...",
    log_btn_save: "Save Log",
    log_success: "Log saved successfully!",
    log_history: "Recent History",
    log_btn_delete: "Delete",
    admin_tab_tasks: "Routine Mgmt",
    admin_tab_users: "Employees",
    admin_tab_reports: "Global Reports",
    admin_new_user: "New Employee",
    admin_new_task: "New Routine",
    admin_ph_name: "Full Name",
    admin_ph_user: "Username",
    admin_ph_email: "Corporate Email",
    admin_ph_pass: "Access Password",
    admin_ph_title: "Title (e.g., Mechanic)",
    admin_ph_shift: "Shift",
    admin_ph_dept: "Department",
    admin_role_op: "Operator",
    admin_role_adm: "Administrator",
    admin_btn_add_user: "Register",
    admin_ph_task_title: "Activity Title",
    admin_ph_task_desc: "Instructions",
    admin_label_assign: "Assign to:",
    admin_btn_add_task: "Create Routine",
    admin_confirm_user: "Are you sure you want to remove this user?",
    admin_confirm_task: "Are you sure you want to remove this routine?",
    admin_confirm_log: "Are you sure you want to delete this log?",
    admin_responsibles: "assignees",
    admin_type: "Task Type",
    admin_type_check: "Simple Checklist",
    admin_type_meas: "Measurement/Data",
    admin_unit: "Unit (e.g. bar, °C)",
    admin_min: "Min",
    admin_max: "Max",
    admin_export_csv: "Export Data (CSV)",
    report_date: "Date",
    report_user: "User",
    report_type: "Type",
    report_value: "Value",
    report_desc: "Description",
    insights_title: "AI Advisor",
    insights_intro: "Use Artificial Intelligence to analyze scrap patterns, downtime, and team discipline.",
    insights_btn: "Generate Action Plan",
    insights_btn_loading: "Analyzing...",
    insights_result_title: "Generated Strategic Plan",
    insights_empty: "Click the button above to generate insights based on current data.",
    freq_hourly: "HOURLY",
    freq_daily: "DAILY",
    freq_weekly: "WEEKLY",
    freq_monthly: "MONTHLY",
    freq_yearly: "YEARLY"
  },
  es: {
    app_name: "RoutineMaster",
    app_subtitle: "Gestión Industrial",
    login_title: "Gestión de Rutina Industrial",
    login_user: "Email o Usuario",
    login_pass: "Contraseña",
    login_btn: "Entrar",
    login_error_auth: "Credenciales inválidas. Verifique su email y contraseña.",
    login_demo: "Credenciales Demo:",
    nav_dashboard: "Tablero",
    nav_routine: "Mi Rutina",
    nav_logs: "Registros",
    nav_admin: "Gestión y Admin",
    nav_insights: "Asesor IA",
    nav_logout: "Cerrar Sesión",
    dash_title: "Tablero de Control",
    dash_subtitle: "Resumen de disciplina y productividad",
    dash_top_performer: "Colaborador Destacado",
    dash_discipline: "de Disciplina Actual",
    dash_rate: "Tasa de Adhesión",
    dash_team: "del equipo",
    dash_pending: "Tareas Pendientes",
    dash_pending_sub: "Actividades no realizadas en el período",
    dash_ranking: "Ranking de Disciplina (Período Actual)",
    dash_prod_chart: "Volumen de Producción vs Desperdicio (7 días)",
    dash_filter_shift: "Filtrar por Turno:",
    dash_filter_dept: "Filtrar por Sector:",
    dash_all_shifts: "Todos los Turnos",
    dash_all_depts: "Todos los Sectores",
    routine_title: "Mi Rutina",
    routine_subtitle: "Actividades programadas",
    routine_completed: "Completadas",
    routine_empty: "No hay tareas asignadas a usted.",
    routine_overdue: "ATRASADO",
    routine_until: "Hasta",
    routine_placeholder: "Nota (opcional)",
    routine_value_ph: "Valor",
    routine_btn_complete: "Completar",
    routine_status_done: "Hecho",
    routine_out_of_range: "Fuera de rango",
    logs_title: "Registros Operativos",
    logs_subtitle: "Informe datos de producción, ocurrencias y paradas.",
    log_prod: "Producción",
    log_scrap: "Desperdicio",
    log_stop: "Parada",
    log_maint: "Mantenimiento",
    log_label_time: "Tiempo (minutos)",
    log_label_qty: "Cantidad (unidades)",
    log_label_val: "Valor / Cantidad",
    log_label_desc: "Descripción / Nota",
    log_place_desc: "Describa el motivo, código de pieza o detalle...",
    log_btn_save: "Guardar Registro",
    log_success: "¡Registro guardado con éxito!",
    log_history: "Historial Reciente",
    log_btn_delete: "Eliminar",
    admin_tab_tasks: "Gestión de Rutinas",
    admin_tab_users: "Colaboradores",
    admin_tab_reports: "Reportes Globales",
    admin_new_user: "Nuevo Colaborador",
    admin_new_task: "Nueva Rutina",
    admin_ph_name: "Nombre Completo",
    admin_ph_user: "Usuario",
    admin_ph_email: "Email Corporativo",
    admin_ph_pass: "Contraseña",
    admin_ph_title: "Cargo (Ej: Mecánico)",
    admin_ph_shift: "Turno",
    admin_ph_dept: "Departamento",
    admin_role_op: "Operativo",
    admin_role_adm: "Administrador",
    admin_btn_add_user: "Registrar",
    admin_ph_task_title: "Título de la Actividad",
    admin_ph_task_desc: "Instrucciones",
    admin_label_assign: "Asignar a:",
    admin_btn_add_task: "Crear Rutina",
    admin_confirm_user: "¿Está seguro de que desea eliminar este usuario?",
    admin_confirm_task: "¿Está seguro de que desea eliminar esta rutina?",
    admin_confirm_log: "¿Está seguro de que desea eliminar este registro?",
    admin_responsibles: "responsables",
    admin_type: "Tipo de Tarea",
    admin_type_check: "Checklist Simple",
    admin_type_meas: "Medición/Datos",
    admin_unit: "Unidad (ej: bar, °C)",
    admin_min: "Mín",
    admin_max: "Máx",
    admin_export_csv: "Exportar Datos (CSV)",
    report_date: "Fecha",
    report_user: "Usuario",
    report_type: "Tipo",
    report_value: "Valor",
    report_desc: "Descripción",
    insights_title: "Asesor IA",
    insights_intro: "Utilice la Inteligencia Artificial para analizar patrones de desperdicio, paradas y disciplina.",
    insights_btn: "Generar Plan de Acción",
    insights_btn_loading: "Analizando...",
    insights_result_title: "Plan Estratégico Generado",
    insights_empty: "Haga clic en el botón de arriba para generar insights.",
    freq_hourly: "HORA A HORA",
    freq_daily: "DIARIO",
    freq_weekly: "SEMANAL",
    freq_monthly: "MENSUAL",
    freq_yearly: "ANUAL"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
